### ISSUE TITLE
Adding logging 

### ISSUE THREAD

**Issue by vsarunov** [theweavrs/BreadPlayer#101]
It is a suggestion, add logging so it would be easier to identify issues as well as look at the way exception are handled (if they are not swallowed).

**Comment by theweavrs** [comment]
Logging is already there. Look at the BreadLogger.cs file. I used XLog. The only thing that is left is sending the file to be analyzed. Perhaps you have some suggestion?

**Comment by theweavrs** [comment]
I used Mail but that was pathetic obviously because of smtp restrictions. It should be uploaded to some database or some such.
