### ISSUE TITLE
Duplicates window doesn't show title song

### ISSUE THREAD

**Issue by Bond-009** [theweavrs/BreadPlayer#104]
It would be better if you could see the title of the duplicate.
![2017-04-03_10-28-27](https://cloud.githubusercontent.com/assets/21289123/24603482/3edaf4d0-1861-11e7-9a26-c9bd9402fcf3.png)

**Comment by theweavrs** [comment]
The problem comes when there are 20 or 30 duplicates. We can list them all in a message box.

**Comment by Bond-009** [comment]
You are right, but there should be a way to see which songs you delete when you click that button.

**Comment by theweavrs** [comment]
Perhaps a custom dialog box with a listbox?

**Comment by Bond-009** [comment]
Sounds good to me 👍

**Comment by theweavrs** [comment]
Yup. Working on it.

**Comment by theweavrs** [comment]
This should be implemented now in the latest build.

Commit Reference: [54c43ae0](https://github.com/theweavrs/BreadPlayer/commit/54c43ae0cd98636b3331cf9195a0783d672f0c38)

**Comment by theweavrs** [comment]
This is fixed in the latest build. Please feel free to reopen if that is not so.
