### ISSUE TITLE
Crash when seeking slider to the end.

### ISSUE THREAD

**Issue by theweavrs** [theweavrs/BreadPlayer#111]
An unhandled exception occurs when you try to seek to the end of the song.
`Exception Message: Layout cycle detected. Layout could not complete.`

Asking for confirmation:
@vsarunov @Bond-009 @stamlercas @wobbince @coding4u 

Steps to reproduce:
1- Play a song.
2. Directly seek to the very end.
3. Do this for more than one song and repeatedly.
**Update:**
After much debugging, the cause of this error is this block of code in Shell.Xaml.cs:
```csharp
            Window.Current.CoreWindow.PointerPressed += CoreWindow_PointerPressed;
            Window.Current.CoreWindow.PointerMoved += CoreWindow_PointerMoved;
            Window.Current.CoreWindow.PointerReleased += CoreWindow_PointerReleased;
```
These three events control the seeking process. Somehow, in these events a Layout Cycle starts causing the app to crash.

Seeking using the `Thumb's` `DragStarted` and `DragCompleted` events never causes exceptions.

**Update 2:**
The previously mentioned cause was apparently wrong and now after many bouts of testing, it can be reproduced even without those three events.

**Comment by Bond-009** [comment]
It works for me

**Comment by theweavrs** [comment]
try doing it for more than one song and repeatedly.

**Comment by theweavrs** [comment]
Issue confirmed as related to Windows rather than the code. Reinstallation of Windows fixed this. Closing now...
