### ISSUE TITLE
Bug: version 2.1.0, dark theme not work, and app freeze after song loaded.

### ISSUE THREAD

**Issue by cdytoby** [theweavrs/BreadPlayer#123]
2 bugs:
1. when switch to dark theme, theme doesn't change, and after close the app and reopen it, app freeze for about a minute, and crashes.
2. after songs are loaded, app freezes, user must manually close and reopen the app.

**Comment by theweavrs** [comment]
Can confirm. Working on a fix immediately.

**Comment by theweavrs** [comment]
Please make a separate issue for each bug from now on as it helps in keeping track of all the issues.
