### ISSUE TITLE
App crashing at start-up bug

### ISSUE THREAD

**Issue by colinkiama** [theweavrs/BreadPlayer#128]
I had to reset the app data from the settings app for the app to actually stop crashing on start-up. Then to get the lock screen feature working, i had to toggle it a few times. It was working. Unfortunately, after closing and opening the app it keeps crashing at start up. (The cycle continues)

**Comment by theweavrs** [comment]
I will investigate this further.

**Comment by theweavrs** [comment]
@colinkiama are you able to see the what's new dialog?

**Comment by colinkiama** [comment]
Only after resetting the app on the settings app.

Sent from my Windows 10 phone

**Comment by theweavrs** [comment]
Can you please try these steps:
1. Reset the app from the store.
2. Open the app.
3. Wait for the songs to load fully.
4. Go into app Settings > Library.
5. Click on Reset Everything.
6. Close the app.
7. Reopen the app.

Please report after trying these steps out. Were you able to open the app?

**Comment by theweavrs** [comment]
Also, please see if you can find anything in the "Documents > Debug" folder. If there is anything related to BreadPlayer please send as an attachment. Thank you.

**Comment by colinkiama** [comment]
Yes

Sent from my Windows 10 phone

**Comment by theweavrs** [comment]
Have you yet tried the latest nightly build?

**Comment by theweavrs** [comment]
Please download and install the Nighly Build and then try again.

After the app has crashed, [follow these instructions](https://github.com/theweavrs/BreadPlayer/wiki/How-To-Send-The-Log-File-To-Us-From-Mobile) and send me the log file.

**Comment by colinkiama** [comment]
I don't see a log.log file in the app’s local state folder 

Sent from my Windows 10 phone

**Comment by theweavrs** [comment]
@colinkiama are you sure the app crashed and that you installed the latest nightly build? Please give it a try again.

**Comment by theweavrs** [comment]
@colinkiama Try it out this way:
1. Uninstall the app.
2. Install the nightly build.
3. Open the app and wait for it to crash. DO NOT OPEN THE APP AGAIN (That resets the log.)
4. Follow the steps to send the log file.

Thank you so much for all the help.

**Comment by hashhar** [comment]
This works on desktop but still crashes on Windows Mobile. I'll upload the log as soon as I get the chance.

**Comment by hashhar** [comment]
This is the normal store log. [Log.txt](https://github.com/theweavrs/BreadPlayer/files/1098851/Log.txt)

**Comment by hashhar** [comment]
[Log.txt](https://github.com/theweavrs/BreadPlayer/files/1098887/Log.txt)
This is the beta log. [Log.txt](https://github.com/theweavrs/BreadPlayer/files/1098887/Log.txt)

**Comment by theweavrs** [comment]
@hashhar is the app still crashing?

**Comment by hashhar** [comment]
No. I just installed it again from the store this time and haven't seen any crashes yet.

**Comment by theweavrs** [comment]
Closing this as issue has been resolved.
