### ISSUE TITLE
Windows Store Download Link is Invalid

### ISSUE THREAD

**Issue by MathewSachin** [theweavrs/BreadPlayer#133]
The link for downloading BreadPlayer from Windows Store https://www.microsoft.com/en-gb/store/p/bread-player/9nblggh42srx/ is resulting in a 404 (Not Found) page

**Comment by MathewSachin** [comment]
Looks like an issue with the Microsoft servers, same issue arising for other apps.

**Comment by Bond-009** [comment]
Yeah, msdn was down too yesterday.

**Comment by theweavrs** [comment]
It should be working now.
