### ISSUE TITLE
Seek bar not working properly

### ISSUE THREAD

**Issue by DannyTalent** [theweavrs/BreadPlayer#14]
When playing a song and clicking on another area of the seek bar, the audio jumps a bit, but doesn't work as intended.

**What it does:** Small jump in audio, and then goes back to the same place
**What it should do:** Jump to a certain time in the song, where the mouse is clicking

PC, Mobile doesn't work either but there isn't a jump

**Comment by theweavrs** [comment]
Yes, this is still not functional. I will try and play around with things and see what can be done.

**Comment by DannyTalent** [comment]
Ah right, but pulling the button does work, at least on PC

**Comment by theweavrs** [comment]
Yes, I added that to at least make it seekable.

**Comment by theweavrs** [comment]
@DannyTalent Can you please test something? See if the SMTC appear when you minimize the app in mobile. Basically, first play a song then press home button and then try changing the volume. If the song appears there then awesome if not please tell.

**Comment by DannyTalent** [comment]
Nope. No controls

**Comment by theweavrs** [comment]
I have fixed this temporarily, may or may not work for phone. I will check on emulator.
