### ISSUE TITLE
no one can make a setup file from it

### ISSUE THREAD

**Issue by great-ssh** [theweavrs/BreadPlayer#149]
I think this is a bug that no one can make a setup file from it.
please make it possible.
thank you.

**Comment by theweavrs** [comment]
@great-ssh I don't think I fully understand what you mean. This is a UWP app. A setup file for BreadPlayer would make no sense unless I release a version for Windows 7, Linux and Mac.

**Comment by great-ssh** [comment]
Hello, @theweavrs.
You know that this is a UWP app and based on Groove Music.
but i mean no one is going to put it on Microsoft Store because it isn't himselfs or herselfs.
so when a person changes the name and icon or logo and he/she wants to give it to his/her friends, he/she can't because it is made for Microsoft Store.
so no one can use the open source of it and they can go and download ot fro store.

**Comment by theweavrs** [comment]
If you mean that if someone wants to install Bread Player outside of Microsoft Store then it is possible. If you go to the Bread Player [releases web page](https://github.com/theweavrs/BreadPlayer/releases) here on GitHub, you will find an .appxbundle for every release and also a way to install it without Microsoft Store.
