### ISSUE TITLE
Font Capitalization options not displaying properly

### ISSUE THREAD

**Issue by CharlieFoxTwo** [theweavrs/BreadPlayer#151]
### Actual Behaviour:
![bread](https://user-images.githubusercontent.com/30303272/28400044-a150fec6-6cc5-11e7-8015-335a8d9b5be3.PNG)
![bread2](https://user-images.githubusercontent.com/30303272/28400045-a1527274-6cc5-11e7-93a1-c4741704067a.PNG)

### Expected Behaviour:
Readable strings should be shown in combo box. 

### General Information:
1. Bread Player Version: v2.3.0-beta
2. Device Type: PC
3. OS Version: Windows 10 14393.1480

### Additional Comments:
It appears that an Enum is not being converted to strings as expected.

**Comment by theweavrs** [comment]
Yes, I can confirm this. Fixing it right away! Thanks for the report
