### ISSUE TITLE
The App crashed when trying to use the Windows Volume Control Bar

### ISSUE THREAD

**Issue by Max-Wang1** [theweavrs/BreadPlayer#152]
### Actual Behaviour:
The App hang and crashed when trying to use the Windows Volume Control Bar (which appears after pressing the hardware volume up/down button) to pause/skip a song.

![capture](https://user-images.githubusercontent.com/20838218/28424603-9b858f44-6da0-11e7-9d31-56bef646b464.JPG)

#### What Happened?
The app hang and crashed.

#### How it happened?
I tested multiple times and it seems that whenever you try to pause/skip a song using the bar, the crash will happen.

#### What were you expecting?
Please fix the bug, thanks!

### Steps to reproduce the bug:

1. Start the player
2. Press the hardware volume up/down button
3. pause/skip a song using the volume control bar

### General Information:
1. Bread Player Version: 2.3.0-beta
2. Device Type: Windows tablet
3. OS Version: Windows 10 x64 with Creators update
4. Device Model: Surface Pro 4

### Additional Comments:
Thanks for your awesome work!!!

From event viewer:
Faulting application name: BreadPlayer.exe, version: 1.0.0.0, time stamp: 0x595a3506
Faulting module name: twinapi.appcore.dll, version: 10.0.15063.332, time stamp: 0xf873d086
Exception code: 0xc000027b
Fault offset: 0x0000000000095a76
Faulting process id: 0x2944
Faulting application start time: 0x01d3016055df6ce6
Faulting application path: C:\Program Files\WindowsApps\22102thecodrr.BreadPlayer_2.4.0.0_x64__fknyqnmcp2942\BreadPlayer.exe
Faulting module path: C:\WINDOWS\SYSTEM32\twinapi.appcore.dll
Report Id: 4005675f-dab0-4068-870e-1249fba22e63
Faulting package full name: 22102thecodrr.BreadPlayer_2.4.0.0_x64__fknyqnmcp2942
Faulting package-relative application ID: App

**Comment by theweavrs** [comment]
I will look around and see if this can be reproduced. Thanks for reporting.

**Comment by theweavrs** [comment]
Can you kindly attach the log file too? It would be in you `Music Library` under `.breadplayerlogs` folder.

**Comment by CharlieFoxTwo** [comment]
Can confirm that both hardware media controls, as well as pressing the on-screen Windows media controls, cause the app to crash. It doesn't seem to be appearing in the error log.

**Comment by CharlieFoxTwo** [comment]
I fixed it - just a null check on line 187. I pushed a commit but I have never committed to an external project on github before so I have no idea if it worked. Commit is e41f3a96.

**Comment by Max-Wang1** [comment]
@CharlieFoxTwo Thanks!!!
@theweavrs  @CharlieFoxTwo  Please check out the log below.

17:54:44:049|INFO | 2|BLogger|App launched and session started...
17:54:44:065|INFO | 2|BLogger|Navigating to Shell...
17:54:44:065|INFO | 2|BLogger|Content set to Window successfully...
17:54:44:741|INFO | 2|BLogger|App left background and is now in foreground...
17:54:47:716|INFO |10|BLogger|Library successfully loaded!
17:54:48:464|INFO |13|BLogger|Songs successfully imported! Total Songs: 52; Failed: 0; Loaded: 54
17:59:49:919|INFO | 2|BLogger|App has entered background...
17:59:53:300|INFO | 2|BLogger|App left background and is now in foreground...
17:59:57:489|ERROR|13|BLogger|Failed to load file. Loading next file...
17:59:57:573|ERROR| 9|BLogger|Failed to load file. Loading next file...
17:59:57:642|ERROR|13|BLogger|Failed to load file. Loading next file...
17:59:57:707|ERROR| 8|BLogger|Failed to load file. Loading next file...
17:59:57:762|ERROR|10|BLogger|Failed to load file. Loading next file...
17:59:57:790|ERROR|13|BLogger|Failed to load file. Loading next file...
17:59:57:862|ERROR| 9|BLogger|Failed to load file. Loading next file...
17:59:57:936|ERROR| 9|BLogger|Failed to load file. Loading next file...
17:59:58:000|ERROR| 8|BLogger|Failed to load file. Loading next file...
17:59:58:099|ERROR|13|BLogger|Failed to load file. Loading next file...
17:59:58:210|ERROR|10|BLogger|Failed to load file. Loading next file...
17:59:58:280|ERROR| 9|BLogger|Failed to load file. Loading next file...
17:59:58:352|ERROR| 8|BLogger|Failed to load file. Loading next file...
17:59:58:408|ERROR| 9|BLogger|Failed to load file. Loading next file...
17:59:58:489|ERROR|13|BLogger|Failed to load file. Loading next file...
17:59:58:587|ERROR| 9|BLogger|Failed to load file. Loading next file...
17:59:58:621|ERROR|13|BLogger|Failed to load file. Loading next file...
17:59:58:684|ERROR|13|BLogger|Failed to load file. Loading next file...
17:59:58:753|ERROR|10|BLogger|Failed to load file. Loading next file...
17:59:58:806|ERROR| 9|BLogger|Failed to load file. Loading next file...
17:59:58:884|ERROR|10|BLogger|Failed to load file. Loading next file...
17:59:58:938|ERROR|13|BLogger|Failed to load file. Loading next file...
17:59:59:022|ERROR|13|BLogger|Failed to load file. Loading next file...
17:59:59:106|ERROR| 9|BLogger|Failed to load file. Loading next file...
17:59:59:185|ERROR|10|BLogger|Failed to load file. Loading next file...
17:59:59:238|ERROR|15|BLogger|Failed to load file. Loading next file...
17:59:59:354|ERROR| 8|BLogger|Failed to load file. Loading next file...
17:59:59:454|ERROR|15|BLogger|Failed to load file. Loading next file...
17:59:59:538|ERROR|15|BLogger|Failed to load file. Loading next file...
17:59:59:623|ERROR|10|BLogger|Failed to load file. Loading next file...
17:59:59:685|ERROR|10|BLogger|Failed to load file. Loading next file...
17:59:59:754|ERROR|15|BLogger|Failed to load file. Loading next file...
17:59:59:839|ERROR|10|BLogger|Failed to load file. Loading next file...
17:59:59:907|ERROR|10|BLogger|Failed to load file. Loading next file...
17:59:59:939|ERROR|15|BLogger|Failed to load file. Loading next file...
18:00:00:008|ERROR| 9|BLogger|Failed to load file. Loading next file...
18:00:00:054|ERROR| 8|BLogger|Failed to load file. Loading next file...
18:00:00:123|ERROR|10|BLogger|Failed to load file. Loading next file...
18:00:00:204|ERROR|15|BLogger|Failed to load file. Loading next file...
18:00:00:286|ERROR|10|BLogger|Failed to load file. Loading next file...
18:00:00:355|ERROR|10|BLogger|Failed to load file. Loading next file...
18:00:00:424|ERROR|10|BLogger|Failed to load file. Loading next file...
18:00:00:508|ERROR| 9|BLogger|Failed to load file. Loading next file...
18:00:00:571|ERROR|15|BLogger|Failed to load file. Loading next file...
18:00:00:686|ERROR|15|BLogger|Failed to load file. Loading next file...
18:00:00:740|ERROR| 9|BLogger|Failed to load file. Loading next file...
18:00:00:809|ERROR| 8|BLogger|Failed to load file. Loading next file...
18:00:00:925|ERROR| 8|BLogger|Failed to load file. Loading next file...
18:00:01:009|ERROR|15|BLogger|Failed to load file. Loading next file...
18:00:01:087|ERROR| 9|BLogger|Failed to load file. Loading next file...
18:00:01:172|ERROR|15|BLogger|Failed to load file. Loading next file...
18:00:01:172|ERROR|15|BLogger|An error occured while trying to play next song. --> System.ArgumentOutOfRangeException: Arg_ArgumentOutOfRangeException
   at SharedLibrary!<BaseAddress>+0x382f42
   at SharedLibrary!<BaseAddress>+0x3cb4bc
   at BreadPlayer!<BaseAddress>+0xd1754f
   at BreadPlayer.ViewModels.ShellViewModel.GetNextSongInGroup()
   at BreadPlayer!<BaseAddress>+0x124aea9
18:00:55:693|INFO | 2|BLogger|App has entered background...
18:01:13:864|FATAL|19|BLogger|Something caused the app to crash! --> System.NullReferenceException: Arg_NullReferenceException
   at BreadPlayer!<BaseAddress>+0x1243b29
18:14:49:736|INFO | 2|BLogger|App launched and session started...
18:14:49:986|INFO | 2|BLogger|App left background and is now in foreground...
18:14:50:726|INFO | 9|BLogger|Library successfully loaded!
18:14:59:516|INFO | 2|BLogger|App has entered background...
18:15:01:468|INFO | 2|BLogger|App suspended and session terminated. Session length: 0.195456086666667
18:42:11:156|INFO | 2|BLogger|App launched and session started...
18:42:11:171|INFO | 2|BLogger|Navigating to Shell...
18:42:11:171|INFO | 2|BLogger|Content set to Window successfully...
18:42:11:374|INFO | 2|BLogger|App left background and is now in foreground...
18:42:11:918|INFO |10|BLogger|Library successfully loaded!
21:58:59:466|INFO | 2|BLogger|Content set to Window successfully...
21:58:59:963|INFO |15|BLogger|Library successfully loaded!
21:59:15:566|INFO | 2|BLogger|App suspended and session terminated. Session length: 0.268308501666667
22:24:17:751|INFO | 2|BLogger|App suspended and session terminated. Session length: 0.268308501666667
22:24:27:980|INFO | 2|BLogger|App suspended and session terminated. Session length: 0.268308501666667
22:24:53:916|INFO | 2|BLogger|App suspended and session terminated. Session length: 0.268308501666667
22:28:01:996|INFO | 2|BLogger|App suspended and session terminated. Session length: 0.268308501666667
22:29:09:620|INFO | 2|BLogger|App suspended and session terminated. Session length: 0.268308501666667
22:29:46:505|INFO | 2|BLogger|App suspended and session terminated. Session length: 0.268308501666667
22:30:05:587|INFO | 2|BLogger|App suspended and session terminated. Session length: 0.268308501666667
22:31:33:733|INFO | 2|BLogger|App suspended and session terminated. Session length: 0.268308501666667
22:31:57:504|INFO | 2|BLogger|App suspended and session terminated. Session length: 0.268308501666667
22:32:00:729|INFO | 2|BLogger|App suspended and session terminated. Session length: 0.268308501666667
22:32:01:971|INFO | 2|BLogger|App suspended and session terminated. Session length: 0.268308501666667
22:32:30:897|INFO | 2|BLogger|App suspended and session terminated. Session length: 0.268308501666667
22:33:14:052|INFO | 2|BLogger|App suspended and session terminated. Session length: 0.268308501666667
22:33:52:189|INFO | 2|BLogger|App suspended and session terminated. Session length: 0.268308501666667
22:35:03:094|INFO | 2|BLogger|App suspended and session terminated. Session length: 0.268308501666667
22:35:31:754|INFO | 2|BLogger|App suspended and session terminated. Session length: 0.268308501666667
22:35:35:608|INFO | 2|BLogger|App suspended and session terminated. Session length: 0.268308501666667
22:35:37:528|INFO | 2|BLogger|App suspended and session terminated. Session length: 0.268308501666667
22:35:49:859|INFO | 2|BLogger|App suspended and session terminated. Session length: 0.268308501666667
22:36:42:212|INFO | 2|BLogger|App launched and session started...
22:36:42:418|INFO | 2|BLogger|App left background and is now in foreground...
22:40:13:329|INFO | 2|BLogger|App has entered background...
22:40:20:019|INFO | 2|BLogger|App left background and is now in foreground...
22:40:31:593|INFO | 2|BLogger|App has entered background...
22:42:43:913|FATAL|13|BLogger|Something caused the app to crash! --> System.NullReferenceException: Arg_NullReferenceException
   at BreadPlayer!<BaseAddress>+0x1243b29
22:45:07:665|INFO | 2|BLogger|App launched and session started...
22:45:07:665|INFO | 2|BLogger|Navigating to Shell...
22:45:07:852|INFO | 2|BLogger|App left background and is now in foreground...
22:45:08:839|INFO |15|BLogger|Library successfully loaded!
22:45:15:452|FATAL|18|BLogger|Something caused the app to crash! --> System.NullReferenceException: Arg_NullReferenceException
   at BreadPlayer!<BaseAddress>+0x1243b29
22:45:50:208|INFO | 2|BLogger|Content set to Window successfully...
22:45:50:542|INFO | 2|BLogger|App left background and is now in foreground...
22:45:50:968|INFO |15|BLogger|Library successfully loaded!
23:02:56:470|INFO | 2|BLogger|Navigating to Shell...
23:02:56:782|INFO | 2|BLogger|App left background and is now in foreground...
23:02:57:258|INFO | 8|BLogger|Library successfully loaded!
23:05:30:547|INFO | 2|BLogger|App has entered background...
23:05:40:935|INFO | 2|BLogger|App suspended and session terminated. Session length: 2.74124645333333
23:05:49:640|INFO | 2|BLogger|App suspended and session terminated. Session length: 2.74124645333333
23:06:23:846|INFO | 2|BLogger|App suspended and session terminated. Session length: 2.74124645333333
23:08:23:327|INFO | 2|BLogger|App suspended and session terminated. Session length: 2.74124645333333
23:09:20:188|INFO | 2|BLogger|App suspended and session terminated. Session length: 2.74124645333333
23:11:18:377|INFO | 2|BLogger|App suspended and session terminated. Session length: 2.74124645333333
23:16:23:467|INFO | 2|BLogger|App suspended and session terminated. Session length: 2.74124645333333
23:16:36:944|INFO | 2|BLogger|App suspended and session terminated. Session length: 2.74124645333333
23:25:44:088|INFO | 2|BLogger|App suspended and session terminated. Session length: 2.74124645333333
23:25:48:229|INFO | 2|BLogger|App suspended and session terminated. Session length: 2.74124645333333
23:26:00:243|INFO | 2|BLogger|App suspended and session terminated. Session length: 2.74124645333333
23:26:07:137|INFO | 2|BLogger|App suspended and session terminated. Session length: 2.74124645333333
23:26:13:722|INFO | 2|BLogger|App suspended and session terminated. Session length: 2.74124645333333
23:26:23:190|INFO | 2|BLogger|App suspended and session terminated. Session length: 2.74124645333333
23:26:28:441|INFO | 2|BLogger|App suspended and session terminated. Session length: 2.74124645333333
23:26:30:051|INFO | 2|BLogger|App suspended and session terminated. Session length: 2.74124645333333
23:26:55:373|INFO | 2|BLogger|App suspended and session terminated. Session length: 2.74124645333333
23:32:03:581|INFO | 2|BLogger|App left background and is now in foreground...
23:32:05:896|INFO | 2|BLogger|App has entered background...
23:32:06:268|INFO | 2|BLogger|App suspended and session terminated. Session length: 2.74124645333333
00:14:16:744|INFO | 2|BLogger|App launched and session started...
00:14:17:371|INFO | 9|BLogger|Library successfully loaded!
00:14:32:779|INFO | 2|BLogger|App suspended and session terminated. Session length: 0.26724063
08:07:54:517|INFO | 2|BLogger|App launched and session started...
08:07:55:074|INFO |10|BLogger|Library successfully loaded!
08:08:15:384|INFO | 2|BLogger|App suspended and session terminated. Session length: 0.34766495
08:08:25:693|INFO | 2|BLogger|App suspended and session terminated. Session length: 0.34766495
08:21:23:106|INFO | 2|BLogger|App suspended and session terminated. Session length: 0.34766495
08:21:48:587|INFO | 2|BLogger|App suspended and session terminated. Session length: 0.34766495
08:22:00:517|INFO | 2|BLogger|App suspended and session terminated. Session length: 0.34766495
08:22:19:050|INFO | 2|BLogger|App suspended and session terminated. Session length: 0.34766495
08:22:25:048|INFO | 2|BLogger|App suspended and session terminated. Session length: 0.34766495
08:31:32:915|INFO | 2|BLogger|App suspended and session terminated. Session length: 0.34766495
08:31:42:211|INFO | 2|BLogger|App suspended and session terminated. Session length: 0.34766495
08:31:46:144|INFO | 2|BLogger|App suspended and session terminated. Session length: 0.34766495
09:49:54:977|INFO | 2|BLogger|App suspended and session terminated. Session length: 0.34766495

**Comment by Max-Wang1** [comment]
I tried to reproduce the bug a again, and this time I got a NullReferenceException. Seems that the ArgumentOutOfRangeException is another bug.


11:12:43:922|INFO | 2|BLogger|App launched and session started...
11:12:44:197|INFO | 2|BLogger|App left background and is now in foreground...
11:12:44:774|INFO |14|BLogger|Library successfully loaded!
11:12:50:276|FATAL|17|BLogger|Something caused the app to crash! --> System.NullReferenceException: Arg_NullReferenceException
   at BreadPlayer!<BaseAddress>+0x1243b29
11:13:31:263|INFO | 2|BLogger|App launched and session started...
11:13:31:480|INFO | 2|BLogger|App left background and is now in foreground...
11:13:32:208|INFO |14|BLogger|Library successfully loaded!
