### ISSUE TITLE
App crash (cause unknown)

### ISSUE THREAD

**Issue by CharlieFoxTwo** [theweavrs/BreadPlayer#154]
Just something I found in my error log. Not sure what caused it. I'll keep an eye out for it in the future.

### General Information:
1. Bread Player Version: v2.3.0-beta
2. Device Type: PC
3. OS Version: Windows 10 14393.1480

### Additional Comments:
From log:
19:44:51:183|INFO | 3|XLog.LogManager|>>> LogManager initialized successfully. UTC time: Fri, 21 Jul 2017 02:44:51 GMT
19:44:51:192|INFO | 3|BLogger|Events initialized. Progressing in app constructor.
19:44:51:240|INFO | 3|BLogger|Content set to Window successfully...
19:44:51:228|INFO | 3|BLogger|App launched and session started...
19:44:51:240|INFO | 3|BLogger|Navigating to Shell...
19:44:52:156|INFO | 3|BLogger|App left background and is now in foreground...
19:44:53:744|INFO |17|BLogger|Library successfully loaded!
19:44:57:376|INFO | 3|BLogger|App has entered background...
19:44:57:382|FATAL| 3|BLogger|Something caused the app to crash! --> System.Runtime.InteropServices.COMException (0x80073DC8): The size of the state manager setting value has exceeded the limit.

Error trying to write application data container value
   at System.Runtime.InteropServices.WindowsRuntime.IMap``2.Insert(K key, V value)
   at System.Runtime.InteropServices.WindowsRuntime.MapToDictionaryAdapter.Insert[K,V](IMap``2 _this, K key, V value)
   at System.Runtime.InteropServices.WindowsRuntime.MapToDictionaryAdapter.Indexer_Set[K,V](K key, V value)
   at BreadPlayer.CoreWindowLogic.SaveSettings()
   at BreadPlayer.App.App_EnteredBackground(Object sender, EnteredBackgroundEventArgs e)

**Comment by theweavrs** [comment]
This is caused when BreadPlayer tries to save some setting on entering background state. Somehow the application data container which holds the settings has exceeded the maximum size limit and so this exception is being raised. I will look for a fix! Thanks for reporting.
