### ISSUE TITLE
Bass dll not found exception

### ISSUE THREAD

**Issue by touseefbsb** [theweavrs/BreadPlayer#159]
System.DllNotFoundException: 'Unable to load DLL 'bass': The specified module could not be found. (Exception from HRESULT: 0x8007007E)'

I got this exception when I tried to debug. exception occurred in file "BASSPlayerEngine.cs" at line 254.

get => Bass.ChannelBytes2Seconds(_handle, Bass.ChannelGetPosition(_handle));  //Line 254

**Comment by theweavrs** [comment]
That means you have not placed the specified bass.dll in the correct directory.  You should reclone and try to debug again.

**Comment by theweavrs** [comment]
Closing this as it has been inactive for over 2 months.
