### ISSUE TITLE
Seek backwards does not function as expected

### ISSUE THREAD

**Issue by charliefoxtwo** [theweavrs/BreadPlayer#164]
### Actual Behaviour:
Seeking backwards plays the song that was last played

#### How it happened?
1. If you start the app, play a song, and then try to seek backwards, it won't go anywhere.
2. If you are shuffling, and then turn shuffle off and seek backward, it will play the song that was last played.

### Expected Behaviour:
1. If shuffle is off, the song directly before the song you are trying to play in your playlist should be played. If shuffle is on, the shuffle index should advance backwards.
2. The previous song in the playlist, **not** the previously played song, should be played.

### General Information:
1. Bread Player Version: v2.5.0-betaa
2. Device Type: PC
3. OS Version: Windows 10 14393.1480

### Additional Comments:
This goes in line with our previous conversation about reworking the entire shuffle method. When shuffle is enabled, the active playlist should become a shuffled playlist. When you skip in shuffle, you should advance to the next index. When you reach the end of the shuffled playlist (provided repeat is on), it should start again from index 0, **not** rebuild the playlist. When you turn shuffle off, the active playlist reverts to a standard non-shuffled playlist.

**Comment by theweavrs** [comment]
I copied this behavior from Groove Music Player. Basically, we are playing from history when you tap on Previous button. I have been thinking on how to improve this as I, too, am frustrated when nothing happens on seeking backwards.

>  When you reach the end of the shuffled playlist (provided repeat is on), it should start again from index 0, not rebuild the playlist. 
I think rebuilding the playlist is essential here. Or else you will be going through the same indexes and same songs again and again. That beats the purpose of a shuffle function.

**Comment by charliefoxtwo** [comment]
@theweavrs I have started working on my implementation of shuffle. Basically, whenever you toggle the shuffle button, it rebuilds the playlist (to shuffled vs non-shuffled). This allows you to seek forward and backward without managing a history, as it just advances to the next index in either direction. So far it seems to be working. 

I can see how rebuilding the playlist might be a beneficial function, but I would argue it's not necessary. If your playlist is too small, it might play the same song close to twice in a row. If your playlist is too large, you won't notice. To my knowledge, all other music players just generate the playlist when shuffle is toggled, and I've never had a problem with it... But that's just me, ymmv. 

As an aside, skip on shuffle is also working, just not persisting. I'll look into the solution you provided and then merge with the latest branch... Hopefully the "songs not playing"  issue will resolve itself!

**Comment by theweavrs** [comment]
>Hopefully the "songs not playing" issue will resolve itself!
That issue has been resolved :)

I will look into your implementation once you PR it and see if it is better or worse. There is a question, why would you want to shuffle backwards? Doing so is unnecessary, you would always shuffle forward and the backward button would be used for when you want to listen to the previous song again. The history comes into play there.

Currently, shuffle only works on the main library so if you managed to implement it for the currently playing playlist, that would be wonderful.

As for rebuilding the playlist, I agree that it is not necessary so...yep. I will see if it can be removed.

Thanks.

**Comment by theweavrs** [comment]
I just comitted the changes to not rebuild the collection on reaching the end. [commit](https://github.com/theweavrs/BreadPlayer/commit/3dd1266b96edb539b1d9e6ae14d5fc7d6fe2a0e6)

**Comment by charliefoxtwo** [comment]
@theweavrs I think the ability to skip backwards when shuffling (if a little odd) is certainly better than nothing happening when skipping backwards. It not that you would *want* to do it, so much as you would *not want* nothing to happen when doing it, intentionally or otherwise.

**Comment by theweavrs** [comment]
I think a better approach might be to just play the song from the history and when the history ends, start shuffling backwards. Same approach for the non-shuffle environment. Play from the history until in ends and then play the previous song.

**Comment by charliefoxtwo** [comment]
@theweavrs all seems to be working now, except my quick and dirty implementation broke shuffle in playlist (I'm not surprised - I just threw it together to see if it would work). I'll keep working on that.

The other issue that I'm running into is that if you enable skip on shuffle in a playlist, it doesn't seem to propagate outside of that playlist until you restart (both visually and in practice). I'm not sure why yet.

Regarding playing from history, I think then I would only be able to skip backward so far in shuffle before I reached the end, right? In Deezer, for example, I can turn on shuffle, and then skip backward as much as I want - even if there are no songs in my "history", it will just increment backwards through the playlist. I see this as a much less confusing and much more foolproof implementation, but that's just my opinion and maybe everybody else would prefer it differently. I'm certainly open to being proven wrong.

Maybe we should do a poll, and figure out how people expect it to act or want it to act? Maybe a setting to allow you to toggle between the two modes?

**Comment by theweavrs** [comment]
Making it a setting would just confuse users.

Now that I think about it...there is no need for a history. Basically, when we shuffle and seek forward, we are increment the index by 1 and not a random number. So it stands to reason that the previous song will always be `CurrentIndex - 1`. And it will work the same way when we are not shuffling. So...history is not even needed as it is an extra step.

I will work on an implementation that takes the history out of the play and works in a much simpler manner.

As for the issue you are having, I cannot tell until I see your code.

**Comment by charliefoxtwo** [comment]
@theweavrs I've got a fork on my profile because I have no idea wtf I'm doing with github or how pull requests work lol. I'll push the code to there soon, and you can take a look at what I've done. I haven't deleted the history, I'm just... not using it lol. It could really be cleaned up, but at least you could take a look and see my implementation.

**Comment by charliefoxtwo** [comment]
@theweavrs pushed to my fork https://github.com/charliefoxtwo/BreadPlayer/commit/e465b7eb47833280d8f5efc7cba9b75a44ad45e5

**Comment by theweavrs** [comment]
@charliefoxtwo Is the `SkipOnShuffle` property song specific?

**Comment by theweavrs** [comment]
@charliefoxtwo Make a PR so I can properly review your edits and changes. There are a lot of code improvements that can be implemented in your code.

Here's how to open a PR:
![clickhere](https://user-images.githubusercontent.com/7473959/29005903-1cb17860-7aff-11e7-8b98-26d5cc76c12c.PNG)

**Comment by charliefoxtwo** [comment]
@theweavrs it was a **really** messy implementation, so go nuts lol https://github.com/theweavrs/BreadPlayer/pull/166

**Comment by theweavrs** [comment]
Closing as it was completed.
