### ISSUE TITLE
Windows 10 mobile - App dominates the 950XL device

### ISSUE THREAD

**Issue by cadayton** [theweavrs/BreadPlayer#170]
#### What Happened?
Just playing around with the App, but the app dominates the device to the degree that the device must be power cycled.  The device is a 950XL.

#### How it happened?
Just executing the app.

### Expected Behaviour:
I expect to be able to put the app in the background and use other applications currently.

#### What were you expecting?
Ditto.

### Steps to reproduce the bug:

1. 
2. 
3.

### General Information:
1. Bread Player Version:   Don't have a clue the app doesn't provide that info or it is very well hidden.
2. Device Type:
3. OS Version:  Window 10 Mobile
4. Device Model:  950XL

### Additional Comments:
This is basic running of a app without taking total control of the device.  I would think this is basic 101 user interface design stuff.   Also when submitting an issue,  if version, model and etc... info is desired  have the app report those details so it can be easily communicated.   I looked for 15 to 20 minutes and could not determine the version of the Bread Player that is installed so I gave up.

**Comment by theweavrs** [comment]
Hi,

If you could please provide the log file also, I would appreciate it very much. It will be in your `Music` folder under `.breadplayerLogs` folder. 

As for version problem, you are kinda right. It is not very well placed but I am working on a better UX so you won't have that problem. In case you still need to know the version, it will be in Settings > About.

**Comment by cadayton** [comment]
HI,

Attached is the log.  Thanks.  Now I know where to find the version info.

Craig Dayton
cadayton@protonmail.com
360-466-8778
paypal.me/CraigDayton

Sent with [ProtonMail](https://protonmail.com) Secure Email.

**Comment by theweavrs** [comment]
@cadayton sorry can't see any attached files. Can you please mail me the log at enkaboot@gmail.com? Thanks

**Comment by theweavrs** [comment]
@cadayton  is this still happening in the latest versions?

**Comment by cadayton** [comment]
I'll download the latest and get back to you.

Craig Dayton
cadayton@protonmail.com
360-466-8778
paypal.me/CraigDayton

Sent with [ProtonMail](https://protonmail.com) Secure Email.

**Comment by cadayton** [comment]
Did a clean install of 2.7.3.0 and it loaded the 3483 songs in a normal expected amount of time.  Overall this is much improved the prior version because I can play some songs, but there are still some issues that I've discovered so far.

Really like the lyrics feature.  I'm still exploring and discovering the other features.

1. Song play pauses in the middle of the song for unknown reason.  Sometime it will start backup on its own and sometimes the play button has to be pressed again.

2. Search feature has big delay in character echoing.  Likely because it is trying to guess the word that I'm typing.  Cool feature that it is trying to guess the word being typed but it comes at the expense of not being able to see the character that is typed in a timely fashion.

3. Search feature is not returning all of the artist's songs when typed.  For instance, 'Tom Petty' search would display some albums but only a subset of songs on the album.

4. When the phone goes into lock mode, the app freaks out does not display its normal interface after the lock is removed. I only had this happen once and it didn't repeat later.

I'll have to log some more time with the app to become more familiar with all the options.
Also found it annoying, the app was immediately prompting to rate it after using it for 5 seconds.

One feature that I'm looking for in music player app is the automatic generation of a smart list based on the number of times a song is played.  I pretty much given up on creating playlist because it takes so long to create and often after an update the playlists get wipe out or no longer functional.  Anything that could be done to automate the creation of custom playlists would be great feature to consider.

I'll update you with other issues that I discover.

Craig Dayton
cadayton@protonmail.com
360-466-8778
paypal.me/CraigDayton

Sent with [ProtonMail](https://protonmail.com) Secure Email.

**Comment by theweavrs** [comment]
closing as it seems fixed. Reopen if that is not the case.
