### ISSUE TITLE
播放列表的奇偶行表现混乱了

### ISSUE THREAD

**Issue by jevonsflash** [theweavrs/BreadPlayer#171]
#### What Happened?
播放列表的奇偶行表现混乱了

#### How it happened?
当我在这个控件拖动排序歌曲后，两个本应该交替表现的样式堆积在一起了

### Expected Behaviour:
应该重新使两个样式交替出现

#### What were you expecting?
重新刷新AlternatingRowListView这个控件的样式呈现吧

### Steps to reproduce the bug:

1. 在所有涉及这个控件的地方都会出现这个bug

### General Information:
1. Bread Player Version:v 2.5.0 beta
2. Device Type: Win10 
3. OS Version: 10586
4. Device Model: PC

**Comment by theweavrs** [comment]
Closing this as it is fixed in the previous releases.
