### ISSUE TITLE
Mobile - Pressing the back button puts the application into the background.

### ISSUE THREAD

**Issue by Pantherinae** [theweavrs/BreadPlayer#172]
No matter where you are within the app pressing the back button on mobile makes the app go into the background.
Wouldn't the expect behaviour be if I go into settings, press the back button it should return to the home or to where you were previously?

**Comment by theweavrs** [comment]
@Pantherinae this is strange. I fixed this issue a while back. Will investigate and see if it can be reproduced.

**Comment by Pantherinae** [comment]
@theweavrs I should of specified which back button im talking about. Which is the Phone back button not bread player back button.

**Comment by theweavrs** [comment]
@Pantherinae Meant the same. I removed the BreadPlayer back button precisely because the Phone Back button worked. 😄

**Comment by Pantherinae** [comment]
@theweavrs What version did you remove it from? Cause the current build I have still has the Bread Player back button.

**Comment by theweavrs** [comment]
@Pantherinae What build do you have? I can't see it in 2.6.1.

**Comment by Pantherinae** [comment]
@theweavrs 2.1.6-beta on a Lumia 950xl on with display at 350%

**Comment by theweavrs** [comment]
This is fixed and pushed for 2.7.0 release.
