### ISSUE TITLE
Cover doesn't update if next song is coverless

### ISSUE THREAD

**Issue by Bond-009** [theweavrs/BreadPlayer#19]
If you play a song with a cover and after that one without is still shows the cover of the last song

**Comment by theweavrs** [comment]
Thanks for reporting this bug! Can you please give a screenshot where this bug occurs?

**Comment by theweavrs** [comment]
@DannyTalent can you reproduce this?

**Comment by DannyTalent** [comment]
On mobile, nope. It shows an icon when it has no cover... On pc, well you'll have to wait a few hours..

**Comment by theweavrs** [comment]
@DannyTalent Okay thanks!

**Comment by Bond-009** [comment]
I just tested it, some songs that are coverless have the cover of 1 other song while other coverless songs don't have a cover. (another music player displays them correctly)
![applicationframehost_2016-10-27_19-41-59](https://cloud.githubusercontent.com/assets/21289123/19778546/8dff6c72-9c7d-11e6-8c1a-3dad3cb70774.png)
![applicationframehost_2016-10-27_19-42-41](https://cloud.githubusercontent.com/assets/21289123/19778547/8dffce10-9c7d-11e6-9f14-d9d68aaeaa99.png)
