### ISSUE TITLE
About a broken link on readme.md

### ISSUE THREAD

**Issue by cpxPratik** [theweavrs/BreadPlayer#192]
LInk for `Windows Universal Apps` on https://github.com/theweavrs/BreadPlayer#build-notes is broken. https://developer.microsoft.com/en-us/windows/apps may be the right one.

Twitter link would be great since i surf dev-related stuff through twitter, no need necessarily though.

**Comment by theweavrs** [comment]
Thanks for the report. I fixed it just now. As for the twitter link, will add it ASAP. Here's the twitter link if you need it: [BreadPlayer Twitter](https://twitter.com/yourbreadplayer)
