### ISSUE TITLE
It Crashes

### ISSUE THREAD

**Issue by trbryant** [theweavrs/BreadPlayer#216]
### Actual Behaviour:
Open Bread Player, I click on the magnifying glass (search) and I type "Minimalist" in the search bar and hit enter.  Search results return with Bakers, Breads and Toasts with the "Show All" dialog to the right.  I click Show All next to Bakers
#### What Happened?
_[Write detailed explaination of what actually happened. Did the app crash? Did the app hang? etc.]_
The app crashes and it returned to the main home screen
#### How it happened?
_[Write detailed explaination of how the problem occured. What were you doing? When did it happen? etc.]_
I opened the application rand through the steps listed about and it crashed.
### Expected Behaviour:
Expecting to be able to add podcasts to listen
#### What were you expecting?
_[Write in detail what you were expecting from BreadPlayer when the problem occured.]_
Expecting the show all dialog to work
### Steps to reproduce the bug:

1. Alcatel Idol 4 Running Windows 10 Mobile 10.0.15254.1
2. Open the application
3. Try to add new podcasts

### General Information:
1. Bread Player Version: 2.7.6.0-beta
2. Device Type: Alcatel Idol 4
3. OS Version: 10.0.15254.1
4. Device Model:Alcatel Idol 4

### Additional Comments:
_[Any additional information to help us hunt down and fix the bug?]_

**Comment by theweavrs** [comment]
I will investigate this right away. Fix coming soon. :)

**Comment by theweavrs** [comment]
Can you please provide the log? It will be in your Music Library under .breadplayerLogs folder. It will be a file named BreadPlayer.log. Send that to me at: enkaboot@gmail.com.

Thanks.

**Comment by theweavrs** [comment]
Was fixed in v2.7.8
