### ISSUE TITLE
An icon (was made) but all suggestions welcome!

### ISSUE THREAD

**Issue by theweavrs** [theweavrs/BreadPlayer#3]
~~Something with an **M** will suffice. **Any person with any experience in designing is welcome to contribute.**~~ 

_The new Icon was made with the suggestion of the new name and so this issue no longer remains but please note that any new ideas or contribution is always welcome. This is not to discourage or disappoint but only to inform._

**Note:**
**_If you do not like the new icon or have any new suggestions or just want to share ideas, please do not hesitate to [email me](mailto:enkaboot@gmail.com) or open a new issue. Your contribution will always be met with appreciation and applause._**

**Comment by RoyalArdor** [comment]
Here you go :)
[macalifa_logo.zip](https://github.com/theweavrs/Macalifa/files/505134/macalifa_logo.zip)
-Paul Michael Pupo

**Comment by theweavrs** [comment]
That's actually an amazing logo, really appreciate it.

If you have time can you please make something like this:
![stock-vector-m-letter-symbol-m-letter-icon-m-letter-template-384959272](https://cloud.githubusercontent.com/assets/7473959/19023551/3d9a5502-890a-11e6-870a-ef066857fe51.jpg)
Maybe something like the second icon in the first row or the second in the third row? Your choice of course, if you have time.

**Comment by RoyalArdor** [comment]
Yea, I'll give it a shot soon!

**Comment by theweavrs** [comment]
That'd be amazing! Thank you so much!

**Comment by RoyalArdor** [comment]
Hello, sorry for the MIA. I like the second one with the gradient in this attachment. :)
[MACALIFA_LOGOS.zip](https://github.com/theweavrs/BreadPlayer/files/526234/MACALIFA_LOGOS.zip)

**Comment by RoyalArdor** [comment]
Make sure you view it on a white background, such as drag and dropping into a browser.

**Comment by theweavrs** [comment]
We changed the App name to **Bread Player** just this week (so sorry) but these all are fantastic. I understand that a lot of time was put into all these, for that I personally apologize.

**Comment by theweavrs** [comment]
_The new Icon was made with the suggestion of the new name and so this issue no longer remains but please note that any new ideas or contribution is always welcome. This is not to discourage or disappoint but only to inform._

**Note:**
**_If you do not like the new icon or have any new suggestions or just want to share ideas, please do not hesitate to [email me](mailto:enkaboot@gmail.com) or open a new issue. Your contribution will always be met with appreciation and applause._**
