### ISSUE TITLE
Make breadplayer use the windows audio controls, especially on mobile

### ISSUE THREAD

**Issue by MightyK1337** [theweavrs/BreadPlayer#31]
Using windows audio controls, we can change the song anywhere, especially on the lockscreen without opening the app. currently we need to go to bread player to change the song. Also, we get overlapping songs, when songs are played on a different player, when bread player is also running.

**Comment by theweavrs** [comment]
You are talking about SMTC. Yes, I am still trying to make those work, there seems to be some problem that they do not appear. In PC on the other hand, they do appear (if you press the volume up/down button on your keyboard if it is there.).

As for overlapping songs, I will try and research about that. BreadPlayer uses Un4Seen Bass so it is quite different and when you play a song from another player, Bass isn't disturbed. Maybe there is a way to know when another sound is being played and we can stop the playback. Let's see.

**Comment by theweavrs** [comment]
@MightyK1337 I was able to add basic support for SMTC, I may release a new alpha in a few days. Its getting pretty stable for an alpha, don't you think? I played around with Bread for more than an hour, playing and doing all kinds of stuff. It never crashed even once. But I know an hour is too less a play time. 

Anyways, @Bond-009 @DannyTalent @MightyK1337 there is still a lot of testing left. Specifically the Playlist area. Would you mind going through that?

Thank you by the by for all the effort and support. I really really appreciate it; without you guys Bread would have been just another player eating dust.

**Comment by MightyK1337** [comment]
Currently v0.1.4 is crashing very frequently to the point of being unusable. So if a later version with all the new changes is published, it would be easier to test.
