### ISSUE TITLE
Bread Player crashing while loading huge number of songs

### ISSUE THREAD

**Issue by MightyK1337** [theweavrs/BreadPlayer#32]
I have about 1500 songs in my music folder. Bread player crashes after loading around half of the songs. This is making the app almost unusable.

**Comment by theweavrs** [comment]
This is strange, there must be some corrupt song or empty song there on which BreadPlayer crashes. I will try and add an exception handler around this.

**Comment by MightyK1337** [comment]
Also there is this crashing issue when sorting the songs. the app almost always crashes when sorting.

**Comment by theweavrs** [comment]
Yup! I fixed that a few minutes ago.

**Comment by Bond-009** [comment]
I installed the latest release added my songs and it crashed while loading them. Now, the app crashes each time it starts.

**Comment by theweavrs** [comment]
@Bond-009 @DannyTalent Sorry for replying so late 😞 I was so busy with the player, didn't find any time to actually reply.

Anyways, I have released a new alpha after continuous development and fixing bugs, and I am certain this one is way more stable than the last (which was a mistake).

I would love it if you guys give it a go! [Alpha-1.6](https://github.com/theweavrs/BreadPlayer/releases/tag/v0.1.6-alpha)
