### ISSUE TITLE
Crash after creation of playlists

### ISSUE THREAD

**Issue by DannyTalent** [theweavrs/BreadPlayer#33]
After about 5 (maybe 6, at most) playlists are very slow to create, for the seventh I used Japanese characters and the app crashed, now it crashes every time I load it... Not sure if it's the number of playlists or the characters (both in name and description)... When opened, the app shows 0 playlists, when you click on the (➕ ) it shows a blank menu (no options) after a few seconds, it becomes unresponsive or crashes

Tried using emoji as names, works fine.

**Comment by theweavrs** [comment]
Yup! Playlists area is still unrefined. Can you elaborate on that slow part? Does the player lag? Or is it a slow process (since you have to add one by one.)?

**Comment by DannyTalent** [comment]
Nvm, they loaded after a few tries, took around 10 seconds and the UI was completely unresponsive during the process. Background music did work fine during this

**Comment by theweavrs** [comment]
Hmm...I will have to reproduce this to fix it. Seems like they are loaded on the UI thread hence the unresponsiveness. Can you reproduce this on PC too? (I hope not.)

**Comment by DannyTalent** [comment]
I have classes till 9pm haha, I will however test it tomorrow as soon as I can!

**Comment by theweavrs** [comment]
Sure! :laughing:
