### ISSUE TITLE
Songs not stopping automatically when they should

### ISSUE THREAD

**Issue by DannyTalent** [theweavrs/BreadPlayer#40]
This is mobile only. There's 2 things that come with this bug:

1. When playing a file on BP and then trying to play another one on, for example, Groove, or playing a game which normally stops music, the music doesn't stop. Consequently, the songs overlap.
2. When this happens, SMTC only shows info for the new song (the one playing on Groove) or none at all (for example, after playing a video) and then the song must be paused or BP manually closed (which by the way stops playback, not sure if this is intended)

**Comment by DannyTalent** [comment]
It doesn't happen both ways, however (i.e. if I'm playing a song on Groove and then try playing it on BP, the Groove song **does** stop)

**Comment by theweavrs** [comment]
If Groove can stop music then it is certainly possible. I will look around...maybe there is a way.
