### ISSUE TITLE
PlayBar show/hide button not visible in phones with software buttons

### ISSUE THREAD

**Issue by theweavrs** [theweavrs/BreadPlayer#41]
![screen](https://cloud.githubusercontent.com/assets/7473959/20444700/e7c34544-adf3-11e6-8b4b-91af9b2e6077.png)

_Tested on emulator with 4.0 inch screen._

**Comment by DannyTalent** [comment]
Works normally on L735

**Comment by theweavrs** [comment]
Must be a glitch with the emulator then.
