### ISSUE TITLE
Clicking on the end of the progressbar doesn't work

### ISSUE THREAD

**Issue by Bond-009** [theweavrs/BreadPlayer#44]
If you click on the end (last 2sec or so) of the progress bar the song just keeps playing and doesn't go to the end.

![2016-11-22_20-33-30](https://cloud.githubusercontent.com/assets/21289123/20538950/a09812c8-b0f3-11e6-9ee7-a5666078e057.gif)

**Comment by theweavrs** [comment]
I can reproduce this and I am working on it.
