### ISSUE TITLE
Shuffle doesn't work in Music Library

### ISSUE THREAD

**Issue by Bond-009** [theweavrs/BreadPlayer#46]
If you press shuffle in the Music Library it throws an ArgumentOutOfRangeException

![2016-11-22_21-34-13](https://cloud.githubusercontent.com/assets/21289123/20540979/8a60e61c-b0fb-11e6-8b48-234ecd498744.png)

**Comment by theweavrs** [comment]
This was also fixed, coming in the next alpha.
