### ISSUE TITLE
Controls in preview not enabled

### ISSUE THREAD

**Issue by Bond-009** [theweavrs/BreadPlayer#47]
The controls in the preview are not enabled when playing from the Music Library, but the normal controls are enabled.
![applicationframehost_2016-11-22_21-52-00](https://cloud.githubusercontent.com/assets/21289123/20541658/7b8fa7ce-b0fe-11e6-8836-0162d816ba1d.png)
![2016-11-22_21-50-54](https://cloud.githubusercontent.com/assets/21289123/20541659/7b906010-b0fe-11e6-9013-d6adbe5e0531.png)

**Comment by DannyTalent** [comment]
Minimizing and then pressing the volume button on keyboard/device (thus opening the W10 SMTC) seems to fix this, oddly...
![image](https://cloud.githubusercontent.com/assets/23058301/20544561/abb68254-b0d8-11e6-99c3-cf4f47fa1a64.png)
