### ISSUE TITLE
Crash when clicking on menu item with empty library

### ISSUE THREAD

**Issue by Bond-009** [theweavrs/BreadPlayer#50]
I have build the app from source and when I click on Recently Played, Music Library or My Albums when my library is empty the app crashes.

**Comment by hildebrandt87** [comment]
You click back and forth between Recently Played, Music Library or My Albums ? 
In which function stops the debugger ?

**Comment by theweavrs** [comment]
Yes, I can reproduce this.

For the moment, [just delete this line.](https://github.com/theweavrs/BreadPlayer/blob/master/BreadPlayer.Core/ViewModels/LibraryViewModel.cs#L467)
