### ISSUE TITLE
Next crashes the app

### ISSUE THREAD

**Issue by Bond-009** [theweavrs/BreadPlayer#52]
#51 isn't really fixed, it's better now but sometimes it crashes the app
ex: press +-5 times next and it crashes

**Comment by theweavrs** [comment]
Yes, it does crash. I will investigate this further.

**Comment by theweavrs** [comment]
[This commit](https://github.com/theweavrs/BreadPlayer/commit/dda74dd4cfff6e0173541977eb4fe55ef59ace62) should fix the bug.

**Comment by Bond-009** [comment]
It doesn't crash the app anymore but now it sometimes pauses the song.

![2016-11-27_12-00-35](https://cloud.githubusercontent.com/assets/21289123/20647905/2b04b008-b499-11e6-8c70-fd3d36781d9a.gif)

**Comment by Bond-009** [comment]
Still not fixed, it still pauses.

**Comment by Bond-009** [comment]
It still pauses, but it doesn't happen as often anymore.

**Comment by Bond-009** [comment]
First time it happens it gives this error

![2016-12-01_21-02-51](https://cloud.githubusercontent.com/assets/21289123/20810436/095a7fc2-b80a-11e6-9239-0932b78364ee.png)

**Comment by theweavrs** [comment]
Can you make sure that the songs on which it occurs are complete and not corrupt? Also, check if it happens on the same songs again and again.

_I could reproduce this by clicking on the next button repeatedly *really* fast. Is it the same for you?_

**Comment by Bond-009** [comment]
If the player is paused next works, if it's playing klicking on the next button repeatedly really fast pauses it.

**Comment by theweavrs** [comment]
@Bond-009 I will see if I can reproduce this again. Thanks for reporting.

**Comment by Bond-009** [comment]
I think i found the issue (and a second bug), some song get loaded 2 times and it pauses on the second one.
![applicationframehost_2016-12-02_19-06-24](https://cloud.githubusercontent.com/assets/21289123/20844896/71eab080-b8c2-11e6-971d-0592b929ec3a.png)

**Comment by theweavrs** [comment]
Can you make sure this song is loaded 2 times always? And also that this bug occurs on this song always.

**Comment by Bond-009** [comment]
@theweavrs there are multiple double song and each time I restart the player it are different ones.

**Comment by theweavrs** [comment]
@Bond-009 Are you using the most recent build? I noticed it just today after implementing the sort functions.

**Comment by Bond-009** [comment]
Yes I am

**Comment by theweavrs** [comment]
I gotta track this down. *sigh*

**Comment by theweavrs** [comment]
@Bond-009 Join [BP's Gitter Chat Room](https://gitter.im/BreadPlayer/Lobby).

**Comment by Bond-009** [comment]
I downloaded the latest nightly and I think it's fixed.
