### ISSUE TITLE
Album covers not loading

### ISSUE THREAD

**Issue by DannyTalent** [theweavrs/BreadPlayer#56]
![image](https://cloud.githubusercontent.com/assets/23058301/20762533/ab2a1ce8-b6f4-11e6-93a5-0ca6e3d45409.png)

On 0.1.7 (PC)
I've noticed a few things, the rest in here are minor, so I wasn't sure if I should've created a separate issue for each!
1. Album covers aren't loading - Tried
2. Version still says v0.1.6.1-alpha
3. One thing that was pretty cool back in 1.4 is that the music folder was "preselected" when you clicked on "Import from a folder", now you have to manually click the Music folder on the explorer and adds one more click to perform the same action...
4. The blue square sometimes overlaps the text, as you can see in the image

**Comment by theweavrs** [comment]
I cannot reproduce issue no. 1 as all my album arts are loading perfectly but I will check this further.
I forgot to update the version no.
As for no. 3 I was also curious why this is happening, I will tinker around a bit and see if the behaviour can be turned around.

**Comment by DannyTalent** [comment]
Try uninstalling and reinstalling BP... I do that every time there's a new alpha

Btw is there a place where I can submit a logo that maybe you can use? I redid the same logo because it looks a bit aliased (the bp)

**Comment by theweavrs** [comment]
imgur will do fine or you can upload it here (quality isn't decreased).

**Comment by DannyTalent** [comment]
Just here? Well here it is:
![rect4147](https://cloud.githubusercontent.com/assets/23058301/20763439/08987516-b6f8-11e6-92d0-cdb51d562f0e.png)
And here's in SVG for if you do end up using it 👍 
[bp_logo.zip](https://github.com/theweavrs/BreadPlayer/files/622509/bp_logo.zip)

**Comment by theweavrs** [comment]
Thanks for the logo, I will certainly use it 😄 

As you can see below, all album arts are loading fine:
![testing](https://cloud.githubusercontent.com/assets/7473959/20763606/86eb2b76-b74c-11e6-9238-103ae936dc73.PNG)

**Comment by DannyTalent** [comment]
Glad to help!
![image](https://cloud.githubusercontent.com/assets/23058301/20763765/6a2135f6-b6f9-11e6-9131-da958fa90751.png)
Hmm, maybe there's something wrong with my library... It does load the songs normally but... It doesn't go through the "Loading album arts" step

**Comment by theweavrs** [comment]
@DannyTalent Oh! I removed that step because it was slower overall. It loads the library in one step now.

**Comment by DannyTalent** [comment]
Well, I restarted, uninstalled and tried reinstalling but now it's stuck at 98% for some reason... Let's see if someone else can reproduce this

**Comment by theweavrs** [comment]
@DannyTalent That's strange. You should close the installer and run it again.

**Comment by theweavrs** [comment]
@DannyTalent I am sure the issue is in "Always show icons, not thumbnails" because the player saves thumbnails as album arts. I will have to read albumarts from ID3 tags to fix this.

Thanks a lot.

**Comment by DannyTalent** [comment]
Yeah, I thought so, too...
Helps for future issues!
