### ISSUE TITLE
Bread Player bypasses all equalizer settings

### ISSUE THREAD

**Issue by DannyTalent** [theweavrs/BreadPlayer#57]
On mobile, the global equalizer doesn't seem to work, for BP only. Neither does audio virtualization and, I assume, dolby headphones.

**Comment by theweavrs** [comment]
@DannyTalent Yes, it is quite impossible to make those work as BP uses a different audio API underneath. For global equalizer to work, BP would have to use same old MediaPlayer API. Equalizer will be implemented in the upcoming Beta.
