### ISSUE TITLE
Songs not following logical order

### ISSUE THREAD

**Issue by DannyTalent** [theweavrs/BreadPlayer#59]
When sorting by:

- Year
- Album
- Artist

The songs don't follow a logical order, instead they follow an order as if they were sorted by Title.
Unsorted and Title do work fine, though.

![image](https://cloud.githubusercontent.com/assets/23058301/20812974/b2b2c3d2-b7e1-11e6-8364-e478a8b96556.png)

**Comment by theweavrs** [comment]
Confirmed and in progress.
