### ISSUE TITLE
Jump Lists on Year sort unnecessary / need change

### ISSUE THREAD

**Issue by DannyTalent** [theweavrs/BreadPlayer#60]
There's no point on having an A to Z jumplist when sorting by year, since every year is an integer... Maybe make it so the jump list shows each year (similar to the photos app, but without the months part)

**Comment by theweavrs** [comment]
I am still working on the Year sort. Apparently, the library that I have has more songs with empty Year tag than with filled so it is a little harder to test.

Working on this...

**Comment by theweavrs** [comment]
@DannyTalent Join the [BP's Gitter Chat Room](https://gitter.im/BreadPlayer/Lobby) to stay updated (also so that testing gets a little easier 😄 ).
