### ISSUE TITLE
SMTC stops showing the song after loading

### ISSUE THREAD

**Issue by DannyTalent** [theweavrs/BreadPlayer#64]
I tried to change songs while loading a resource intensive app on phone (Instagram) and once I did so, smtc stopped updating the song name. The songs do change, but not the titles.

Managed to reproduce this
An app restart seems to fix it

**Comment by theweavrs** [comment]
Confirmed.

**Comment by theweavrs** [comment]
@DannyTalent Please recheck this issue in the nightly build.

**Comment by DannyTalent** [comment]
The nightly build is downloaded via the link on the description, right?

If that's the case, then no, not fixed. Background smtc is not even working
Btw I've just started working so I won't be as available as before (until march) for testing :/

**Comment by theweavrs** [comment]
@DannyTalent This is certainly troubling as SMTC is working perfectly at my end though I haven't tried with a Release Build, so I will test again. 

As for your unavailability, I can understand so no worries. Test whenever you get time. 😄

**Comment by DannyTalent** [comment]
Alright... I tried to download the nightly build again but instead I got an xml file that says Blob not found :o

**Comment by theweavrs** [comment]
@DannyTalent It should be working now, probably was updated the build.

**Comment by DannyTalent** [comment]
Fixed, closing
