### ISSUE TITLE
Settings crashes the app

### ISSUE THREAD

**Issue by Bond-009** [theweavrs/BreadPlayer#65]
Pressing the settings button results in a crash.

**Comment by DannyTalent** [comment]
Latest version? Try reinstalling? Mine works fine...

**Comment by Bond-009** [comment]
@DannyTalent I build from source :)

**Comment by theweavrs** [comment]
@Bond-009 It is working fine here too. Try debugging and see what's the exception.

**Comment by Bond-009** [comment]
I redeployed it and now it works.
