### ISSUE TITLE
Crash on start sometimes.

### ISSUE THREAD

**Issue by stamlercas** [theweavrs/BreadPlayer#71]
Sometimes when I build, I get:
Exception thrown: 'System.InvalidOperationException' in System.ObjectModel.dll ("Cannot change ObservableCollection during a CollectionChanged event.")
Exception thrown: 'System.Exception' in System.ObjectModel.dll ("Catastrophic failure (Exception from HRESULT: 0x8000FFFF (E_UNEXPECTED))")

**Comment by hildebrandt87** [comment]
How often happens this behavior in the build process ?
Have you ever created the project again? Or reloaded the project code?
one more way: try to replace the dll/reinstall .net 4.5 ( Please take care with this option)

**Comment by theweavrs** [comment]
@stamlercas @hildebrandt87 This is an issue with `GroupedObservableCollection` but it only occurs in Debug mode. I haven't seen this happening in Release Mode but you are welcome to try.

Thanks for reporting :)

**Comment by stamlercas** [comment]
@hildebrandt87 It happens about 1 out of 3 builds and yes I have. @theweavrs Thanks for the response. It has yet to happen in release mode, but I will let you know if that changes.

**Comment by theweavrs** [comment]
@stamlercas  @hildebrandt87 This should be fixed in the latest release. Please confirm and close the issue.

**Comment by theweavrs** [comment]
I am closing this for now as it cannot be reproduced now. Feel free to reopen this if otherwise.
