### ISSUE TITLE
Beta Feature List: Features-To-Be-Added

### ISSUE THREAD

**Issue by theweavrs** [theweavrs/BreadPlayer#75]
## Planned feature list for the upcoming Beta release:

- [x] 1. Equalizer/Effects
- [x] 2. Most Played, Recently Added, Favorites and Now Playing section
- [x] 3. Prevent screen from locking.
- [x] 4. Stop playing after this song. _**(thanks to vsarunov)**_
- [ ] 5. .lrc lyrics (Synchronized lyrics) and unsynced lyrics.
- [ ] 6. Ability to hide a specific folder and its songs.
- [x] 7. Private Playlists
- [x] 8. Ability to relocate (change location) of a song.
- [x] 9. Fade in/out when changing the song.
- [x] 10. Last.fm Scrobbling.
- [ ] 11. SoundCloud Support
- [x] 12. Manual adding of Album arts
- [x] 13. Separate BreadPlayer.Core from BreadPlayer.Views.UWP
- [x] 14. A preview for previous song just like for next song. _**(thanks to vsarunov)**_
- [x] 15. A notification for upcoming song when the position reaches last 15-10 seconds.
- [ ] 16. _Initiate Android Support._
 
_Note: All of these features might not reach the next Beta and some might be postponed due to obvious reasons. **Any help regarding these features including testing, research, code contribution, will be highly appreciated.**_

**Comment by Bond-009** [comment]
I will start with 13, ok?

**Comment by theweavrs** [comment]
@Bond-009 That is the first thing we got to do before we jump to others. Would appreciate all the help :)

**Comment by vsarunov** [comment]
@theweavrs  Btw I started looking at Nr. 4. Hope nobody started yet.

**Comment by theweavrs** [comment]
Started working on no. 12

**Comment by theweavrs** [comment]
**Done with 12.**
Starting #3.

**Comment by theweavrs** [comment]
**Done with 3**
Starting another extra (and secret) feature 😉

**Comment by theweavrs** [comment]
**Done with the extra feature.**
Starting No. 6

**Comment by theweavrs** [comment]
We are now in feature-freeze so no more features will be added until next beta! Please refer to [Guide for Testers](https://github.com/theweavrs/BreadPlayer/wiki/Guide-For-Testers) if you want to help out in testing. The list will be constantly updated.
