### ISSUE TITLE
 Program does not start when file is moved

### ISSUE THREAD

**Issue by hildebrandt87** [theweavrs/BreadPlayer#78]
I import an mp3 file from any path ( for example C:\folder1\subfolder1) , played that song and then i delete it. In the next step, I will close breadplayer. Move the mp3 file to another Folder (C:\folder2\subfolder2). 
Now I try to start the program but it wont work.
![image](https://cloud.githubusercontent.com/assets/12720910/21565231/8aef88b0-ce95-11e6-804a-cac67c64ff9c.png)

The Method "public static async void LoadSettings(bool onlyVol = false, bool play = false)" 
Still tries to load the old path

**Comment by theweavrs** [comment]
This is tested and confirmed. Of course, we can handle it in an exception handler but I wish there was a way to know where the file was moved. Maybe, we can open a FilePicker to ask the user to relocate the last playing file if they want?

**Comment by Bond-009** [comment]
But he deleted it from BreadPlayer so you shouldn't add it back in.

**Comment by theweavrs** [comment]
@Bond-009 I see what you mean. @hildebrandt87 If you delete a song from the library, that doesn't stop the song from playing (should it?), it just plays on. Perhaps, we can stop the song when it is deleted in the library?

**Comment by hildebrandt87** [comment]
@theweavrs jop thats true, the song still goes on if i delete it. Maybe this is a possibility how we can handle the problem. Another possibility would be to implement a check to  the method "LoadSettings"  if the file is not found to continue the startup.
