### ISSUE TITLE
Seperate BreadPlayer.Core and BreadPlayer.Views

### ISSUE THREAD

**Issue by theweavrs** [theweavrs/BreadPlayer#8]
Seperating `BreadPlayer.Core` as a **PCL** and `BreadPlayer.Views.UWP` would make more sense if we want to work with Xamarin and Mono later on. 

_This is relatively easy but time consuming, so any contribution regarding this is highly appreciated._

**Comment by Bond-009** [comment]
I have tried it: https://github.com/Bond-009/BreadPlayer/tree/Dev
Is this what you want or do I need to do it differently?

**Comment by theweavrs** [comment]
@Bond-009 This is a good start, I will write a more detailed explanation to guide you.

Basically, we have to separate all the UI specific code into BreadPlayer.Views.UWP and all the non-UI code into BreadPlayer.Core (Portable Class Library).

To be more specific, **.Views will contain all the ViewModels and the Views, all .xaml files, HamburgerMenu, Extensions, Dialogs, Behaviours, and other code that connects these.**

**Comment by Bond-009** [comment]
@theweavrs ThreadSafeObservableCollection gives me a lot of trouble, it uses Windows.UI.Core and it's used in Core features

**Comment by theweavrs** [comment]
@Bond-009 `CoreDispatcher` is the culprit here as it is platform-specific. We will have to implement an alternative to replace this. For instance [an extension class for `Task` or `SynchronizationContext`](http://stackoverflow.com/a/19226432).

**Comment by Bond-009** [comment]
Should we merge it now and build upon it or should we wait?

**Comment by theweavrs** [comment]
The codebase won't expand much now until the beginning of beta version. I think we should wait for now until the Beta to avoid any additional bugs.

**Comment by Bond-009** [comment]
This is done, right?

**Comment by theweavrs** [comment]
yup.
