### ISSUE TITLE
Player crash when using "Open Song Location"

### ISSUE THREAD

**Issue by hildebrandt87** [theweavrs/BreadPlayer#81]
I got some mp3 files in a folder saved on my desktop. If i want to use the function "open song location" the program crashes. 
![image](https://cloud.githubusercontent.com/assets/12720910/21582125/3f94ad60-d04c-11e6-9552-0a9f1a410b53.png)
This method is in "sharedLogics.cs"

**Comment by hildebrandt87** [comment]
Maybe we can use here the Filepicker /Folderpicker to get access ?
Here are some information that i found : https://msdn.microsoft.com/en-us/library/windows/apps/hh967755.aspx

**Comment by theweavrs** [comment]
@hildebrandt87 Cannot reproduce this. I put a song in a folder on my desktop and then loaded that into library. After that I used `Open Song Location` and it succeeded flawlessly. I tried 2 more times and the same outcome.

**Comment by hildebrandt87** [comment]
I have now reloaded the current source code again.The project is reloaded and deployed. Now it's working :)  I probably had a tilted position. Sorry, i will close this issue.
