### ISSUE TITLE
DRM protected songs showing up, but not playing

### ISSUE THREAD

**Issue by DannyTalent** [theweavrs/BreadPlayer#84]
I have a Groove Music Pass and have a few songs downloaded, naturally, they're all DRM locked, so, even though they appear on the library on Bread, they won't play, and show as 0:01 length
![wp_ss_20170111_0001](https://cloud.githubusercontent.com/assets/23058301/21859822/272c99ec-d7fc-11e6-8c32-98dd51d8ab46.png)

The player does not automatically go to the next song, as well

**Comment by theweavrs** [comment]
I will be sure to add a check for DRM protection and not to add those into library. Later on we can add removal of DRM (on user's consent and responsibility).

**Comment by theweavrs** [comment]
fixed.
