### ISSUE TITLE
Tapping (+) button plays the song

### ISSUE THREAD

**Issue by DannyTalent** [theweavrs/BreadPlayer#85]
...which doesn't feel like normal behavior... (happens on mobile, haven't tried PC)
Normally I think it'd not affect playback and just show the list of playlists...

Also if there's no playlists it just shows a small square

**Comment by theweavrs** [comment]
This was influenced from Groove where on selecting a song it starts playing. What do you think, was the previous behavior better?

**Comment by DannyTalent** [comment]
Yeah that's okay, what I mean is that it shouldn't when you're actually tapping to add a playlist, a user won't  necessarily want to start the song when he's trying to add it to a playlist, but pressing anywhere else should be okay.

Something like this:
![image](https://cloud.githubusercontent.com/assets/23058301/21875591/2e08f96e-d84b-11e6-9dcc-01a1342eeba5.png)

**Comment by theweavrs** [comment]
Fixed the link, try it now.
