### ISSUE TITLE
Not all songs are loading

### ISSUE THREAD

**Issue by MightyK1337** [theweavrs/BreadPlayer#88]
Hi..

long time no see.

I downloaded the latest alpha version 1.1.0 and i am still facing this issue, which I think i have raised before but do not remember ;)

Basically i have around 1400 songs in library. but only around 200 of them are showing up and quite a few of them are duplicates. I tried adding only the folder, but then the player crashes and it again tries loading all the songs.

**Comment by theweavrs** [comment]
Sorry for the late reply, your issue got mixed up. Can you please try again with the nightly builds and confirm this?
