### ISSUE TITLE
Issues as reported by a valuable redditor matjojo1000 (long-list)

### ISSUE THREAD

**Issue by theweavrs** [theweavrs/BreadPlayer#89]
_EDIT: I see now that this is quite the long list, no bad feelings meant, the app works really well and you are certainly doing a good job on it!_
I installed it on my PC a couple things I saw in the first hour:
- [x] it's not really clear how to add new songs
   - I like the fact that the text is the button, but some(including me) might see it as an extension of the text above
   - when clicking the text I get a popup for adding a new folder, but it took so long to come up that I eventually had over 10 'select folder' windows
   - Maybe only allow having one of those open at a time?
- [x] My albums loads endlessly, first without any songs added, and now with my songs loaded(1600+) loading songs takes really really long.
   - the problem might be with my HDD, but 1600+ songs which are in total only 16,4 gigs should not take 5 minutes to load in
song properties:
- [x] I can't edit the tags although they are in a textbox?
   - The tag 'Original Filename' should just be 'Filename' IMO, there is nothing original about that name, if I change the name, would it save every iteration of the text that was in the name?
- [x] the play and add to playlist buttons are in another place every time.
- [x] the now playing icon is HUGE AS F**K.
   - I'd say you are better off using the play button in front of the name
- [ ] no auto scrolling to the song I'm listening to
   - not even when I click next in the app itself and it's not automatically done in the background.
hamburger option menu in open state standard?
- [x] no tooltips on hamburger menu?
   - the only tooltip I could find was on the previous song button
- [x] I'd like to see the previous button get the same preview window as the next song button
- [x] I'd like to see the complete UI colour changes between songs? (this might be based on something in the song, but I can't figure out on what.)
- [x] sort by seems to not work
   - sort by artist suddenly changes to LeadArtist when selected
- [x] 'Genre: All genres' misses a 'G' and doesn't do anything when clicked even though it does have an on_click event
- [x] Colours seem to screw up sometimes (that '...' should have been a ?, not trying to be annoying)
- [x] Colours of the 'play mode selection' button do not follow the scheme of the 'shuffle' mode next to it
   - meaning that I feel like it should be a toggle that turns a bit darker just like that other one next to it
songs that is not playing seems to be selected even though I did not click it ('...' should be 'playing' there might be something wrong with my image editing software)
- [ ] When the song name is longer than there is space for it does not wrap.
- [x] No replacement string for the 'year' tag.
- [x] Nothing Baking shows even when there is something baking
- [ ] Sorting by title does not understand that 151 is higher then 2 (also, '09' sorts as '0')
- [x] no sorting by song length
- [x] plus button switches places: below and then behind
- [x] does not listen to play, pause, previous, and next buttons on neither of my two keyboards (one has dedicated buttons, the others are embedded into it's F-keys, and can be used by pressing the FN key)
   - funnier even, it let's the not playing foobar2K use the keys.
- [x] the 'quick scroll' function when sorting on title does not have the # and & keys in the right place
- [ ] no 'double sorting'
   - meaning that you cannot sort on artist and in artist on album
- [x] it also misses track number sorting
- [x] there is an asterisk before 'name' in the name playlist window even though the one other option is already explicitly set to optional.
- [x] clicking on the 'playlists' button when there is no playlist does not create a new playlist
- [x] even after an hour the 'My Albums' menu has not loaded
- [x] play and add to playlist buttons cut off song name when not neccesary
- [x] a lot of free space behind the tags
- [x] Too much memory allocation. (100 MB RAM usage seems quite a bit, when pressing next and prev some times it even goes up to 200MB).
I just found the settings tab:
- [x] theme button changes nothing, not when 'change accent...' is on and not when it is off.
- [x] turning off 'change accent...' locks the accent into the current colour, not the system wide one
   - this might be by design, if so add another option for locking the accent to the system colour
- [x] Does not seem to load all the album arts, for some albums it works, others it does not.
- [x] App startup crash. (_App does not load anymore, crashes without notion every time I try to load it._)
- [x] Too much memory allocation on startup. (_The app only loads correctly when I quickly click to the settings page. It then proceeds to use a lotttt of processing power, creates a lot of heat, when that stops(fans go to just about 0% again) can I safely go to the library again._)
- [x] Deleting a playlist gives you a confirmation, there is no name of the playlist in the confirmation. so you don't know what playlist you are deleting.

_I will attach the originally attached images later._

**Comment by matjojo** [comment]
Wow, thanks a lot. I kinda was afraid I'd look like a dick by posting so many things at once. If you want I can sort these issues from the suggestions and sort them into the correct issues that you premade?

**Comment by theweavrs** [comment]
@matjojo That would help a lot!

**Comment by theweavrs** [comment]
Please try out the latest version and see if you come up with any new bugs :) Thanks a lot.
