### ISSUE TITLE
Implement toast or progressbar for library import progress (Suggestions Welcome)

### ISSUE THREAD

**Issue by theweavrs** [theweavrs/BreadPlayer#96]
We have absolutely no implementation of progress reporting.

Possible Implementations:

1. A toast like in Material Design.
2. A loading overlay until the app has done loading (not very feasible for big collections).
3. Perhaps the Now Playing screen can act as a progress reporter too. (too hidden).
4. Loading %age under the "Import Folders Into Library" button. (too far)
5. A progressbar in the header of LibraryView. (better)
6. The toggle button to hide/show playbar can hide a progressbar for progress reporting. (better).

**All suggestions welcome!**

**Comment by theweavrs** [comment]
For now, I went with 2 but we will change it later.

**Comment by MightyK1337** [comment]
5 would be better.

**Comment by theweavrs** [comment]
This is done.
