### ISSUE TITLE
[Suggestions needed] What would be the best place to display the equalizer?

### ISSUE THREAD

**Issue by theweavrs** [theweavrs/BreadPlayer#98]
1. An overlay over all of the player.
2. In the settings panel.
3. A small panel just above the PlayBar in the corner of the player.

Give your suggestion below, also if you have any other suggestion do tell.

**Comment by Bond-009** [comment]
Maybe something like this:
![2017-02-18_17-06-04](https://cloud.githubusercontent.com/assets/21289123/23095130/0b7a3e8a-f605-11e6-92b3-ad511225aabf.gif)

**Comment by theweavrs** [comment]
@Bond-009 that is actually the most suitable as it doesn't obstruct play controls OR the library. Thanks a lot.

**Comment by tazcob** [comment]
I agree with @Bond-009.
Another suggestion would be like an option icon near the music control buttons, selecting it would be the equalizer menu on top of everything else.

**Comment by theweavrs** [comment]
This is done.
